### ISSUE TITLE
Error: expected ';' before 'display'

### ISSUE THREAD

**Issue by sebswed** [jigsawnz/Arduino-Multitasking#1]
I receive the following error: expected ';' before 'display'
I use IDE 1.6.7 with an Arduino Mega (in case that makes any difference)
I receive the error when verifying and when trying to upload.
No changes have been made to the file with the exception of the .ino file name

I don't know what I could have done wrong? Any advise for a noob?

![image](https://cloud.githubusercontent.com/assets/4247556/13199075/42836680-d81b-11e5-9087-ea9e920956d0.png)

**Comment by jigsawnz** [comment]
Im missing a semi colon ; behind drawgraph() it should be drawgraph();

I'm still updating the code now and then and not always testing it right away. Sorry about that.

Cheers,

George

**Comment by jigsawnz** [comment]
Updated version available on github now.

Cheers,

George

**Comment by sebswed** [comment]
Hello George.

Thank you for such a quick reply!
This did indeed solved the issue. I did however received another error but that was inside the chronodot. But I will try to find a solution for that online first.
