### ISSUE TITLE
Chronodot.ccp error: Chronodot.cpp:26:31: error: variable 'daysInMonth'

### ISSUE THREAD

**Issue by sebswed** [jigsawnz/Arduino-Multitasking#2]
The Chronodot library doesn't work "out of the box" with the new Arduino IDE versions. You will need to edit the file Chronodot.cpp. 

Look for a line like this (line 26 in my version of the library):
`static uint8_t daysInMonth [] PROGMEM = { 31,28,31,30,31,30,31,31,30,31,30,31 };`

And edit it to look like this.
`const static uint8_t daysInMonth [] PROGMEM = { 31,28,31,30,31,30,31,31,30,31,30,31 };`

Save the file, close and reopen the Arduino IDE in case you had it open, and that's all.

Source:
[Source 1](http://kawasemicorp.com/BRLC/index.html)
[Source 2](https://forums.adafruit.com/viewtopic.php?f=25&t=75278)

**Comment by jigsawnz** [comment]
If this is an issue you might have to notify the author of the chronodot library.

**Comment by sebswed** [comment]
Hello George.
Thank you for your advice!
I just reported it. My initial thought was to inform others when they try to recreate your project.
But I now reported it to Chronodot (feel free to delete this issue as it is not really related to your project)
[Reported at Chronodot](https://github.com/Stephanie-Maks/Arduino-Chronodot/issues/7)
