### ISSUE TITLE
Display not working

### ISSUE THREAD

**Issue by sebswed** [jigsawnz/Arduino-Multitasking#3]
Hello George.

I had an issue with the display not showing any data even though I use the same libraries in another display project. I noticed a difference between the projects on line 26 in your project.

In your project I see the code
`Adafruit_SSD1306 display( OLED_MOSI, OLED_CLK, OLED_DC, OLED_RESET, OLED_CS );`

I replaced this line with
`Adafruit_SSD1306 display(OLED_RESET);`

After that everything worked as intended. I'm very happy and grateful for your project! :-)

My only question as the noob that I am is, do i now, after I changed the code missing some vital functions (maybe less stable?) or should it be okay with just OLED_RESET?

**Comment by jigsawnz** [comment]
#define OLED_MOSI   9
#define OLED_CLK   10
#define OLED_DC    11
#define OLED_CS    12
#define OLED_RESET 13

+

Adafruit_SSD1306 display( OLED_MOSI, OLED_CLK, OLED_DC, OLED_RESET, OLED_CS
);

tells the library which pins are used to connect the display to the arduino.

this
Adafruit_SSD1306 display(OLED_RESET);

only tells it that one pin is connected.

Email your code to georgetimmermans@gmaildotcom. replace dot with . and i
will have a look if that's ok with you.

**Comment by sebswed** [comment]
Thanks! :-)
Will send you a message

**Comment by jigsawnz** [comment]
sorry, i"m mixing up email adresses. georgetimmermans@outlookdotcom replace
dot with .
